context:
  version: 1.1.12
  python_min: 3.9

package:
  name: lbcta
  version: ${{ version }}

source:
- url: https://files.pythonhosted.org/packages/b9/36/13ee0f99c30e414fdf4d7c4b77791063b7d0981d2e060a83c9d051e3e7af/lbcta-${{ version }}.tar.gz
  sha256: 1b4bf9823139060f4a12f09c9cd2c2e52b33cd0d1e05eb3ac9649c4c0c1a6440

build:
  noarch: python
  number: 0
  script: python -m pip install .
  python:
    entry_points:
      - lbcta-ls = lbCta.scripts.status:main
      - lbcta-recall = lbCta.scripts.recall:main
      - lbcta-query = lbCta.scripts.query:main


requirements:
  host:
  - python ${{ python_min }}.*
  - pip
  - setuptools
  run:
  - python >=${{ python_min }}
  - setuptools

tests:
  - python:
      imports:
        - lbCta
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - lbcta-ls --help
      - lbcta-recall --help
      - lbcta-query --help

about:
  homepage: https://gitlab.cern.ch/lhcb-online/lhcb-online-cta
  summary: LHCb interface to EOS/CTA package
  description: |
    This package implements a set of console scripts to interface with the CERN Tape
    Archive (CTA) in view of listing and recalling files and directories from tape.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
